name: Strategy Metrics Update
on:
  push:
    paths:
      - 'NOTEBOOKS/**'
      - 'METRICS.md'

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      